- name: delete default wp plugins
  shell: >
    if $(wp plugin is-installed {{ item }}) ; then
        wp plugin uninstall {{ item }}
    fi
  args:
    chdir: "{{ project_path }}"
  become_user: www-data
  with_items:
    - hello
    - akismet